"""
reports/report_generator.py - JSON + Markdown pentest report generation
"""

import json
from pathlib import Path
from datetime import datetime
from typing import List

from rich.console import Console

from core.config import ScanConfig, OWASP_CATEGORIES, SEVERITY_SCORES
from core.finding import ScanResults


class ReportGenerator:
    """
    Generates professional pentest-style reports in JSON and/or Markdown format.
    Each finding includes:
      - OWASP Top 10:2025 mapping
      - CWE reference
      - CVSS score / severity rating
      - Proof (request/response snippets)
      - Remediation guidance
    """

    def __init__(self, config: ScanConfig, results: ScanResults, console: Console):
        self.config = config
        self.results = results
        self.console = console
        self.output_dir = Path(config.output_dir)
        self.timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    def generate(self) -> List[str]:
        """Generate all requested report formats. Returns list of file paths."""
        paths = []
        for fmt in self.config.output_formats:
            fmt = fmt.strip().lower()
            if fmt == "json":
                p = self._write_json()
                paths.append(p)
            elif fmt in ("md", "markdown"):
                p = self._write_markdown()
                paths.append(p)
            else:
                self.console.print(f"[yellow]Unknown report format: {fmt}[/yellow]")
        return paths

    # ------------------------------------------------------------------ #
    #  JSON Report                                                        #
    # ------------------------------------------------------------------ #

    def _write_json(self) -> str:
        path = self.output_dir / f"scan_report_{self.timestamp}.json"
        data = self.results.to_dict()
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        if not self.config.quiet:
            self.console.print(f"[green]JSON report:[/green] {path}")
        return str(path)

    # ------------------------------------------------------------------ #
    #  Markdown Report                                                    #
    # ------------------------------------------------------------------ #

    def _write_markdown(self) -> str:
        path = self.output_dir / f"scan_report_{self.timestamp}.md"
        md = self._build_markdown()
        with open(path, "w", encoding="utf-8") as f:
            f.write(md)
        if not self.config.quiet:
            self.console.print(f"[green]Markdown report:[/green] {path}")
        return str(path)

    def _build_markdown(self) -> str:
        r = self.results
        summary = r.summary()
        total = sum(summary.values())
        meta = r.to_dict()["scan_metadata"]

        lines = []

        # ── Title ──────────────────────────────────────────────────────
        lines.append("# Web Application Penetration Test Report")
        lines.append("")
        lines.append("> **Generated by DVWA Scanner v{version}**".format(version=r.scanner_version))
        lines.append("")

        # ── Metadata ───────────────────────────────────────────────────
        lines.append("## Scan Metadata")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Target URL | `{meta['target_url']}` |")
        lines.append(f"| Start Time | {meta['start_time']} |")
        lines.append(f"| End Time | {meta['end_time']} |")
        lines.append(f"| Scanner Version | {meta['scanner_version']} |")
        lines.append(f"| Modules Run | {', '.join(meta['modules_run'])} |")
        lines.append(f"| Security Level | {self.config.security_level} |")
        lines.append(f"| Deep Scan | {'Yes' if self.config.deep_scan else 'No'} |")
        lines.append("")

        # ── Executive Summary ─────────────────────────────────────────
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(
            f"The automated DAST scan of **{meta['target_url']}** identified "
            f"**{total} vulnerability finding(s)** across {len(meta['modules_run'])} security modules. "
            "All findings are mapped to the OWASP Top 10:2025 framework."
        )
        lines.append("")

        if r.stats:
            lines.append(f"**Crawl statistics:** "
                f"{r.stats.get('crawled_pages', 0)} pages, "
                f"{r.stats.get('discovered_forms', 0)} forms, "
                f"{r.stats.get('parameterized_urls', 0)} parameterised URLs.")
            lines.append("")

        # Severity breakdown table
        lines.append("### Severity Breakdown")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        severity_emojis = {
            "Critical": "🔴",
            "High": "🟠",
            "Medium": "🟡",
            "Low": "🔵",
            "Informational": "⚪",
        }
        for sev in ["Critical", "High", "Medium", "Low", "Informational"]:
            emoji = severity_emojis.get(sev, "")
            lines.append(f"| {emoji} {sev} | {summary.get(sev, 0)} |")
        lines.append(f"| **Total** | **{total}** |")
        lines.append("")

        # Risk rating
        risk = self._overall_risk(summary)
        lines.append(f"**Overall Risk Rating: {risk}**")
        lines.append("")

        # OWASP coverage table
        lines.append("### OWASP Top 10:2025 Coverage")
        lines.append("")
        lines.append("| Category | Name | Findings |")
        lines.append("|----------|------|----------|")
        owasp_counts: dict = {}
        for f in r.findings:
            cat = f.get("owasp_category", "Unknown")
            owasp_counts[cat] = owasp_counts.get(cat, 0) + 1
        for cat in sorted(owasp_counts.keys()):
            name = OWASP_CATEGORIES.get(cat, "")
            lines.append(f"| {cat} | {name} | {owasp_counts[cat]} |")
        lines.append("")

        # ── Findings ──────────────────────────────────────────────────
        lines.append("---")
        lines.append("")
        lines.append("## Detailed Findings")
        lines.append("")

        if not r.findings:
            lines.append("> No vulnerabilities detected.")
            lines.append("")
        else:
            # Sort by severity
            severity_order = {
                "Critical": 0, "High": 1, "Medium": 2,
                "Low": 3, "Informational": 4
            }
            sorted_findings = sorted(
                r.findings,
                key=lambda x: severity_order.get(x.get("severity", "Informational"), 5)
            )

            for idx, finding in enumerate(sorted_findings, 1):
                lines.extend(self._finding_to_md(idx, finding))

        # ── Errors ────────────────────────────────────────────────────
        if r.errors:
            lines.append("---")
            lines.append("")
            lines.append("## Scan Errors")
            lines.append("")
            for err in r.errors:
                lines.append(f"- `{err}`")
            lines.append("")

        # ── Appendix ──────────────────────────────────────────────────
        lines.append("---")
        lines.append("")
        lines.append("## Appendix: OWASP Top 10:2025 Reference")
        lines.append("")
        lines.append("| ID | Category |")
        lines.append("|----|----------|")
        for cat_id, cat_name in OWASP_CATEGORIES.items():
            lines.append(f"| {cat_id} | {cat_name} |")
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append(
            "*This report was generated automatically. "
            "All findings should be manually verified before remediation. "
            "Automated scanners may produce false positives and cannot detect all vulnerability classes.*"
        )
        lines.append("")

        return "\n".join(lines)

    def _finding_to_md(self, idx: int, f: dict) -> List[str]:
        severity = f.get("severity", "Unknown")
        severity_emojis = {
            "Critical": "🔴", "High": "🟠", "Medium": "🟡",
            "Low": "🔵", "Informational": "⚪",
        }
        emoji = severity_emojis.get(severity, "")

        lines = []
        lines.append(f"### Finding {idx}: {f.get('title', 'Unknown')}")
        lines.append("")

        # Summary table
        lines.append("| Attribute | Value |")
        lines.append("|-----------|-------|")
        lines.append(f"| Severity | {emoji} **{severity}** |")
        lines.append(f"| CVSS Score | {f.get('cvss_score', 0.0)} |")
        lines.append(f"| OWASP Category | {f.get('owasp_category')} — {f.get('owasp_name')} |")
        cwe = f.get("cwe_id")
        if cwe:
            cwe_link = f"[{cwe}](https://cwe.mitre.org/data/definitions/{cwe.replace('CWE-','')})"
            lines.append(f"| CWE | {cwe_link} |")
        lines.append(f"| URL | `{f.get('url', '')}` |")
        lines.append(f"| Method | `{f.get('method', '')}` |")
        lines.append(f"| Parameter | `{f.get('parameter', '')}` |")
        lines.append(f"| Confidence | {f.get('confidence', '')} |")
        lines.append(f"| Module | {f.get('module', '')} |")
        lines.append(f"| Timestamp | {f.get('timestamp', '')} |")
        lines.append("")

        # Description
        lines.append("#### Description")
        lines.append("")
        lines.append(f.get("description", ""))
        lines.append("")

        # Proof
        proof = f.get("proof", "")
        if proof:
            lines.append("#### Proof of Concept")
            lines.append("")
            lines.append(proof)
            lines.append("")

        # Payload
        payload = f.get("payload", "")
        if payload:
            lines.append("**Payload:**")
            lines.append(f"```\n{payload}\n```")
            lines.append("")

        # Request snippet
        req = f.get("request_snippet", "")
        if req:
            lines.append("**Request:**")
            lines.append(f"```http\n{req}\n```")
            lines.append("")

        # Response snippet
        resp_snip = f.get("response_snippet", "")
        if resp_snip:
            lines.append("**Response (excerpt):**")
            lines.append(f"```\n{resp_snip[:400]}\n```")
            lines.append("")

        # Remediation
        remediation = f.get("remediation", "")
        if remediation:
            lines.append("#### Remediation")
            lines.append("")
            lines.append(remediation)
            lines.append("")

        # References
        refs = f.get("references", [])
        if refs:
            lines.append("#### References")
            lines.append("")
            for ref in refs:
                lines.append(f"- {ref}")
            lines.append("")

        lines.append("---")
        lines.append("")
        return lines

    def _overall_risk(self, summary: dict) -> str:
        if summary.get("Critical", 0) > 0:
            return "🔴 CRITICAL"
        if summary.get("High", 0) > 0:
            return "🟠 HIGH"
        if summary.get("Medium", 0) > 0:
            return "🟡 MEDIUM"
        if summary.get("Low", 0) > 0:
            return "🔵 LOW"
        return "⚪ INFORMATIONAL"